/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum UserDataEvent {
	Uid_Changed = "Uid_Changed",
	Nickname_Changed = "Nickname_Changed",
	Account_Changed = "Account_Changed",
	Password_Changed = "Password_Changed",
	RegisterTime_Changed = "RegisterTime_Changed",
	LastLoginTime_Changed = "LastLoginTime_Changed",
	Coin_Changed = "Coin_Changed",
	Vcoin_Changed = "Vcoin_Changed",
}