/**The class is automatically generated by BatMain.bat , please do not modify */
export const enum NetResponse {
	/**
	 * @param { IUserData }
	 */
	SyncInfo = "SyncInfo",
	/**
	 * @param { HeartOutput }
	 */
	Response_Heart = "Response_Heart",
	/**
	 * @param { RegisterOutput }
	 */
	Response_Register = "Response_Register",
	/**
	 * @param { LoginOutput }
	 */
	Response_Login = "Response_Login",
}