/**This is automatically generated by BatMain.bat , please do not modify */
export const enum ResPath{
	// res/atlas/

	// res/dragonbones/

	// res/font/
	Font01 = "Font01",
	Font_Font01 = "res/font/Font01.ttf",
	Font02 = "Font02",
	Font_Font02 = "res/font/Font02.ttf",
	Font03 = "Font03",
	Font_Font03 = "res/font/Font03.ttf",
	Font04 = "Font04",
	Font_Font04 = "res/font/Font04.ttf",
	Font05 = "Font05",
	Font_Font05 = "res/font/Font05.ttf",
	Font06 = "Font06",
	Font_Font06 = "res/font/Font06.ttf",
	Font07 = "Font07",
	Font_Font07 = "res/font/Font07.ttf",
	Font08 = "Font08",
	Font_Font08 = "res/font/Font08.ttf",
	Font09 = "Font09",
	Font_Font09 = "res/font/Font09.ttf",
	Font10 = "Font10",
	Font_Font10 = "res/font/Font10.ttf",
	Font11 = "Font11",
	Font_Font11 = "res/font/Font11.ttf",
	Font12 = "Font12",
	Font_Font12 = "res/font/Font12.ttf",
	Font13 = "Font13",
	Font_Font13 = "res/font/Font13.ttf",
	Font14 = "Font14",
	Font_Font14 = "res/font/Font14.ttf",

	// res/table/
	Table_Config = "res/table/Config.json",

	// res/ui/
	PkgCommon = "PkgCommon",
	Ui_PkgCommon = "res/ui/PkgCommon",
	PkgGame = "PkgGame",
	Ui_PkgGame = "res/ui/PkgGame",
	PkgLogin = "PkgLogin",
	Ui_PkgLogin = "res/ui/PkgLogin",
	PkgMain = "PkgMain",
	Ui_PkgMain = "res/ui/PkgMain",
	PkgTest = "PkgTest",
	Ui_PkgTest = "res/ui/PkgTest",
}