/**The script is automatically generated by BatMain.bat , please do not modify */
import ComCurrency from "../ui/PkgCommon/ComCurrency";
import ComGongFa from "../ui/PkgMain/ComGongFa";
import ComJueSe from "../ui/PkgMain/ComJueSe";
import ComLingShou from "../ui/PkgMain/ComLingShou";
import ComShiLian from "../ui/PkgMain/ComShiLian";
import ComTipInfo from "../ui/PkgCommon/ComTipInfo";
import ComXiuXing from "../ui/PkgMain/ComXiuXing";
import PkgCommonBinder from "../ui/PkgCommon/PkgCommonBinder";
import PkgGameBinder from "../ui/PkgGame/PkgGameBinder";
import PkgLoginBinder from "../ui/PkgLogin/PkgLoginBinder";
import PkgMainBinder from "../ui/PkgMain/PkgMainBinder";
import RenderGongFa from "../ui/PkgMain/RenderGongFa";
import RenderJueSe from "../ui/PkgMain/RenderJueSe";
import RenderShiLian from "../ui/PkgMain/RenderShiLian";
import UIGameMain from "../ui/PkgGame/UIGameMain";
import UILoginMain from "../ui/PkgLogin/UILoginMain";
import UIMain from "../ui/PkgMain/UIMain";
import UISetting from "../ui/PkgMain/UISetting";
import UITipConfirm from "../ui/PkgCommon/UITipConfirm";
import UIWaiting from "../ui/PkgCommon/UIWaiting";
import { ComCurrencyCtrl } from "../viewCtrl/PkgCommon/Coms/ComCurrencyCtrl";
import { ComCurrencyNetProcessor } from "../viewNetProcessor/PkgCommon/Coms/ComCurrencyNetProcessor";
import { ComCurrencyView } from "../view/PkgCommon/Coms/ComCurrencyView";
import { ComGongFaCtrl } from "../viewCtrl/PkgMain/Coms/ComGongFaCtrl";
import { ComGongFaNetProcessor } from "../viewNetProcessor/PkgMain/Coms/ComGongFaNetProcessor";
import { ComGongFaView } from "../view/PkgMain/Coms/ComGongFaView";
import { ComJueSeCtrl } from "../viewCtrl/PkgMain/Coms/ComJueSeCtrl";
import { ComJueSeNetProcessor } from "../viewNetProcessor/PkgMain/Coms/ComJueSeNetProcessor";
import { ComJueSeView } from "../view/PkgMain/Coms/ComJueSeView";
import { ComLingShouCtrl } from "../viewCtrl/PkgMain/Coms/ComLingShouCtrl";
import { ComLingShouNetProcessor } from "../viewNetProcessor/PkgMain/Coms/ComLingShouNetProcessor";
import { ComLingShouView } from "../view/PkgMain/Coms/ComLingShouView";
import { ComShiLianCtrl } from "../viewCtrl/PkgMain/Coms/ComShiLianCtrl";
import { ComShiLianNetProcessor } from "../viewNetProcessor/PkgMain/Coms/ComShiLianNetProcessor";
import { ComShiLianView } from "../view/PkgMain/Coms/ComShiLianView";
import { ComTipInfoCtrl } from "../viewCtrl/PkgCommon/Coms/ComTipInfoCtrl";
import { ComTipInfoNetProcessor } from "../viewNetProcessor/PkgCommon/Coms/ComTipInfoNetProcessor";
import { ComTipInfoView } from "../view/PkgCommon/Coms/ComTipInfoView";
import { ComXiuXingCtrl } from "../viewCtrl/PkgMain/Coms/ComXiuXingCtrl";
import { ComXiuXingNetProcessor } from "../viewNetProcessor/PkgMain/Coms/ComXiuXingNetProcessor";
import { ComXiuXingView } from "../view/PkgMain/Coms/ComXiuXingView";
import { INetProcessor_Class, IViewCtrl_Class, IView_Class } from "./Interfaces";
import { Logger } from "../../libs/utils/Logger";
import { RenderGongFaView } from "../view/PkgMain/Renders/RenderGongFaView";
import { RenderJueSeView } from "../view/PkgMain/Renders/RenderJueSeView";
import { RenderShiLianView } from "../view/PkgMain/Renders/RenderShiLianView";
import { UIGameMainCtrl } from "../viewCtrl/PkgGame/UIGameMainCtrl";
import { UIGameMainNetProcessor } from "../viewNetProcessor/PkgGame/UIGameMainNetProcessor";
import { UIGameMainView } from "../view/PkgGame/UIGameMainView";
import { UILoginMainCtrl } from "../viewCtrl/PkgLogin/UILoginMainCtrl";
import { UILoginMainNetProcessor } from "../viewNetProcessor/PkgLogin/UILoginMainNetProcessor";
import { UILoginMainView } from "../view/PkgLogin/UILoginMainView";
import { UIMainCtrl } from "../viewCtrl/PkgMain/UIMainCtrl";
import { UIMainNetProcessor } from "../viewNetProcessor/PkgMain/UIMainNetProcessor";
import { UIMainView } from "../view/PkgMain/UIMainView";
import { UISettingCtrl } from "../viewCtrl/PkgMain/UISettingCtrl";
import { UISettingNetProcessor } from "../viewNetProcessor/PkgMain/UISettingNetProcessor";
import { UISettingView } from "../view/PkgMain/UISettingView";
import { UITipConfirmCtrl } from "../viewCtrl/PkgCommon/UITipConfirmCtrl";
import { UITipConfirmNetProcessor } from "../viewNetProcessor/PkgCommon/UITipConfirmNetProcessor";
import { UITipConfirmView } from "../view/PkgCommon/UITipConfirmView";
import { UIWaitingCtrl } from "../viewCtrl/PkgCommon/UIWaitingCtrl";
import { UIWaitingNetProcessor } from "../viewNetProcessor/PkgCommon/UIWaitingNetProcessor";
import { UIWaitingView } from "../view/PkgCommon/UIWaitingView";
import { ViewClass, NetProcessorClass, CtrlClass } from "./UIGlobal";
import { ViewID } from "./ViewID";

const logger = Logger.Create("ViewRegister").setEnable(true);

class ViewRegister {

    Init() {
        this.pkgBind();
        this.viewBind();
        this.registerView();
    }

    /**包bind */
    private pkgBind() {
		PkgCommonBinder.bindAll();
		PkgGameBinder.bindAll();
		PkgLoginBinder.bindAll();
		PkgMainBinder.bindAll();
	}

    /**页面替换bind */
    private viewBind() {
		//Coms
		fgui.UIObjectFactory.setExtension(ComCurrency.URL, ComCurrencyView);
		fgui.UIObjectFactory.setExtension(ComTipInfo.URL, ComTipInfoView);
		fgui.UIObjectFactory.setExtension(ComGongFa.URL, ComGongFaView);
		fgui.UIObjectFactory.setExtension(ComJueSe.URL, ComJueSeView);
		fgui.UIObjectFactory.setExtension(ComLingShou.URL, ComLingShouView);
		fgui.UIObjectFactory.setExtension(ComShiLian.URL, ComShiLianView);
		fgui.UIObjectFactory.setExtension(ComXiuXing.URL, ComXiuXingView);

		//Renders
		fgui.UIObjectFactory.setExtension(RenderGongFa.URL, RenderGongFaView);
		fgui.UIObjectFactory.setExtension(RenderJueSe.URL, RenderJueSeView);
		fgui.UIObjectFactory.setExtension(RenderShiLian.URL, RenderShiLianView);

		//Views
		fgui.UIObjectFactory.setExtension(UITipConfirm.URL, UITipConfirmView);
		fgui.UIObjectFactory.setExtension(UIWaiting.URL, UIWaitingView);
		fgui.UIObjectFactory.setExtension(UIGameMain.URL, UIGameMainView);
		fgui.UIObjectFactory.setExtension(UILoginMain.URL, UILoginMainView);
		fgui.UIObjectFactory.setExtension(UIMain.URL, UIMainView);
		fgui.UIObjectFactory.setExtension(UISetting.URL, UISettingView);
	}

    /**页面注册 */
    private registerView() {
		const register = this.registView;
		//Coms
		register(ViewID.ComCurrencyView, ComCurrencyView, ComCurrencyCtrl, ComCurrencyNetProcessor);
		register(ViewID.ComTipInfoView, ComTipInfoView, ComTipInfoCtrl, ComTipInfoNetProcessor);
		register(ViewID.ComGongFaView, ComGongFaView, ComGongFaCtrl, ComGongFaNetProcessor);
		register(ViewID.ComJueSeView, ComJueSeView, ComJueSeCtrl, ComJueSeNetProcessor);
		register(ViewID.ComLingShouView, ComLingShouView, ComLingShouCtrl, ComLingShouNetProcessor);
		register(ViewID.ComShiLianView, ComShiLianView, ComShiLianCtrl, ComShiLianNetProcessor);
		register(ViewID.ComXiuXingView, ComXiuXingView, ComXiuXingCtrl, ComXiuXingNetProcessor);

		//Views
		register(ViewID.TipConfirmView, UITipConfirmView, UITipConfirmCtrl, UITipConfirmNetProcessor);
		register(ViewID.WaitingView, UIWaitingView, UIWaitingCtrl, UIWaitingNetProcessor);
		register(ViewID.GameMainView, UIGameMainView, UIGameMainCtrl, UIGameMainNetProcessor);
		register(ViewID.LoginMainView, UILoginMainView, UILoginMainCtrl, UILoginMainNetProcessor);
		register(ViewID.MainView, UIMainView, UIMainCtrl, UIMainNetProcessor);
		register(ViewID.SettingView, UISettingView, UISettingCtrl, UISettingNetProcessor);
	}

	private registView(viewId: ViewID, viewCls: IView_Class, ctrlCls?: IViewCtrl_Class, netProcessorCls?:INetProcessor_Class) {
		if (!viewCls) throw new Error("参数不能为空！");
		if (!ViewClass[viewId]) {
			(ViewClass as any)[viewId] = viewCls;
			(CtrlClass as any)[viewId] = ctrlCls;
			(NetProcessorClass as any)[viewId] = netProcessorCls;
		} else {
			logger.warn(`重复添加映射 => ${viewId}`);
		}
	}
}
export const uiRegister = new ViewRegister();