/**The script is automatically generated by BatMain.bat , please do not modify */
export const enum ViewID {
	/**Coms */
	ComCurrencyView = "ComCurrencyView",
	ComTipInfoView = "ComTipInfoView",
	ComGongFaView = "ComGongFaView",
	ComJueSeView = "ComJueSeView",
	ComLingShouView = "ComLingShouView",
	ComShiLianView = "ComShiLianView",
	ComXiuXingView = "ComXiuXingView",

	/**Views */
	TipConfirmView = "TipConfirmView",
	WaitingView = "WaitingView",
	GameMainView = "GameMainView",
	LoginMainView = "LoginMainView",
	MainView = "MainView",
	SettingView = "SettingView",
}