/**The class is automatically generated by BatMain.bat , please do not modify */

declare interface ConfigLangData {
	readonly ID: number;
	/**文本 */
	readonly Text: string;
}

declare interface ConfigLang extends ReadOnlyObject<ConfigLangData> {
	/**账号已存在 */
	readonly 1001: ConfigLangData;
	/**账号不存在 */
	readonly 1002: ConfigLangData;
	/**密码错误 */
	readonly 1003: ConfigLangData;
	/**物品不存在 */
	readonly 1004: ConfigLangData;
	/**物品数量不足 */
	readonly 1005: ConfigLangData;
	/**物品不可使用 */
	readonly 1006: ConfigLangData;
	/**物品不可出售 */
	readonly 1007: ConfigLangData;
	/**商品不存在 */
	readonly 1008: ConfigLangData;
	/**购买商品货币不足 */
	readonly 1009: ConfigLangData;
	/**数量错误 */
	readonly 1010: ConfigLangData;
	/**境界不足，无法穿戴 */
	readonly 1011: ConfigLangData;
	/**当前部位未穿戴装备 */
	readonly 1012: ConfigLangData;
	/**精力不足 */
	readonly 1013: ConfigLangData;
	/**未知类型 */
	readonly 1014: ConfigLangData;
	/**剩余次数不足 */
	readonly 1015: ConfigLangData;
	/**精力已满 */
	readonly 1016: ConfigLangData;
	/**你已经学习了此心法 */
	readonly 1017: ConfigLangData;
	/**境界不足，无法使用 */
	readonly 1018: ConfigLangData;
	/**你已经学习了此技能 */
	readonly 1019: ConfigLangData;
	/**无法学习其他门派的技能 */
	readonly 1020: ConfigLangData;
	/**账号已登录 */
	readonly 1021: ConfigLangData;
}